name: Generate Cron Descriptions

on:
  workflow_dispatch:

jobs:
  cron-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependency
        run: pip install cron-descriptor

      - name: Run cron description script
        run: python cron_description.py
